# Generated by Django 3.2.8 on 2026-04-09 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoOrderConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('enabled', models.SmallIntegerField(default=0)),
                ('meal_slots', models.CharField(blank=True, default='', max_length=64)),
                ('strategy', models.CharField(default='TOP1', max_length=32)),
                ('default_corp_address_id', models.CharField(blank=True, default='', max_length=64)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'auto_order_config',
            },
        ),
        migrations.CreateModel(
            name='AutoOrderJob',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('meal_slot', models.CharField(choices=[('LUNCH', 'LUNCH'), ('DINNER', 'DINNER')], max_length=16)),
                ('trigger_type', models.CharField(default='CRON', max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('RUNNING', 'RUNNING'), ('SUCCESS', 'SUCCESS'), ('PARTIAL', 'PARTIAL'), ('FAILED', 'FAILED')], default='PENDING', max_length=16)),
                ('total_count', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'auto_order_job',
            },
        ),
        migrations.CreateModel(
            name='AutoOrderJobItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED'), ('SKIPPED', 'SKIPPED')], default='PENDING', max_length=16)),
                ('retry_count', models.IntegerField(default=0)),
                ('fail_code', models.CharField(blank=True, default='', max_length=64)),
                ('fail_message', models.CharField(blank=True, default='', max_length=512)),
                ('meican_order_unique_id', models.CharField(blank=True, default='', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'auto_order_job_item',
            },
        ),
        migrations.CreateModel(
            name='CorpAddress',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('namespace', models.CharField(max_length=64)),
                ('address_unique_id', models.CharField(max_length=64)),
                ('address_name', models.CharField(blank=True, default='', max_length=256)),
                ('is_default', models.SmallIntegerField(default=0)),
                ('raw_json', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'corp_address',
            },
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Counters',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dish_id', models.CharField(max_length=64)),
                ('dish_name', models.CharField(max_length=256)),
                ('restaurant_id', models.CharField(blank=True, default='', max_length=64)),
                ('restaurant_name', models.CharField(blank=True, default='', max_length=128)),
                ('price_cent', models.IntegerField(default=0)),
                ('status', models.CharField(default='available', max_length=16)),
                ('tags', models.CharField(blank=True, default='', max_length=256)),
                ('raw_json', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'menu_item',
            },
        ),
        migrations.CreateModel(
            name='MenuSnapshot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('namespace', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('meal_slot', models.CharField(choices=[('LUNCH', 'LUNCH'), ('DINNER', 'DINNER')], max_length=16)),
                ('tab_unique_id', models.CharField(blank=True, default='', max_length=64)),
                ('target_time', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(default='meican', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'menu_snapshot',
            },
        ),
        migrations.CreateModel(
            name='RecommendationBatch',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('meal_slot', models.CharField(choices=[('LUNCH', 'LUNCH'), ('DINNER', 'DINNER')], max_length=16)),
                ('namespace', models.CharField(max_length=64)),
                ('version', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('READY', 'READY'), ('FROZEN', 'FROZEN')], default='READY', max_length=16)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'recommendation_batch',
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.SmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_account',
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('prefers_spicy', models.SmallIntegerField(default=0)),
                ('is_halal', models.SmallIntegerField(default=0)),
                ('is_cutting', models.SmallIntegerField(default=0)),
                ('staple', models.CharField(blank=True, default='', max_length=16)),
                ('taboo', models.CharField(blank=True, default='', max_length=512)),
                ('price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='preference', to='wxcloudrun.useraccount')),
            ],
            options={
                'db_table': 'user_preference',
            },
        ),
        migrations.CreateModel(
            name='UserMeicanAccount',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('meican_username', models.CharField(max_length=128)),
                ('meican_email', models.CharField(blank=True, default='', max_length=128)),
                ('access_token', models.CharField(blank=True, default='', max_length=512)),
                ('refresh_token', models.CharField(blank=True, default='', max_length=512)),
                ('token_expire_at', models.DateTimeField(blank=True, null=True)),
                ('account_namespace', models.CharField(blank=True, default='', max_length=64)),
                ('is_bound', models.SmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='meican_account', to='wxcloudrun.useraccount')),
            ],
            options={
                'db_table': 'user_meican_account',
            },
        ),
        migrations.CreateModel(
            name='RecommendationResult',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rank_no', models.IntegerField()),
                ('score', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('reason', models.CharField(blank=True, default='', max_length=256)),
                ('selected_for_order', models.SmallIntegerField(default=0)),
                ('batch', models.ForeignKey(db_column='batch_id', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='wxcloudrun.recommendationbatch')),
                ('menu_item', models.ForeignKey(db_column='menu_item_id', on_delete=django.db.models.deletion.CASCADE, related_name='recommended_results', to='wxcloudrun.menuitem')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_results', to='wxcloudrun.useraccount')),
            ],
            options={
                'db_table': 'recommendation_result',
            },
        ),
        migrations.CreateModel(
            name='OrderRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('meal_slot', models.CharField(choices=[('LUNCH', 'LUNCH'), ('DINNER', 'DINNER')], max_length=16)),
                ('meican_order_unique_id', models.CharField(blank=True, default='', max_length=64)),
                ('source', models.CharField(choices=[('MANUAL', 'MANUAL'), ('AUTO', 'AUTO')], default='MANUAL', max_length=16)),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('CANCELED', 'CANCELED'), ('FAILED', 'FAILED')], default='CREATED', max_length=16)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.ForeignKey(db_column='menu_item_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='wxcloudrun.menuitem')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='wxcloudrun.useraccount')),
            ],
            options={
                'db_table': 'order_record',
            },
        ),
        migrations.AddConstraint(
            model_name='menusnapshot',
            constraint=models.UniqueConstraint(fields=('namespace', 'date', 'meal_slot'), name='uk_namespace_date_slot'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='snapshot',
            field=models.ForeignKey(db_column='snapshot_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wxcloudrun.menusnapshot'),
        ),
        migrations.AddIndex(
            model_name='corpaddress',
            index=models.Index(fields=['namespace', 'is_default'], name='idx_namespace_default'),
        ),
        migrations.AddField(
            model_name='autoorderjobitem',
            name='job',
            field=models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wxcloudrun.autoorderjob'),
        ),
        migrations.AddField(
            model_name='autoorderjobitem',
            name='menu_item',
            field=models.ForeignKey(db_column='menu_item_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_order_items', to='wxcloudrun.menuitem'),
        ),
        migrations.AddField(
            model_name='autoorderjobitem',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='auto_order_items', to='wxcloudrun.useraccount'),
        ),
        migrations.AddConstraint(
            model_name='autoorderjob',
            constraint=models.UniqueConstraint(fields=('date', 'meal_slot', 'trigger_type'), name='uk_date_slot_trigger'),
        ),
        migrations.AddField(
            model_name='autoorderconfig',
            name='user',
            field=models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='auto_order_config', to='wxcloudrun.useraccount'),
        ),
        migrations.AddConstraint(
            model_name='recommendationresult',
            constraint=models.UniqueConstraint(fields=('batch', 'user', 'rank_no'), name='uk_batch_user_rank'),
        ),
        migrations.AddConstraint(
            model_name='orderrecord',
            constraint=models.UniqueConstraint(fields=('user', 'date', 'meal_slot'), name='uk_user_date_slot'),
        ),
        migrations.AddConstraint(
            model_name='orderrecord',
            constraint=models.UniqueConstraint(fields=('idempotency_key',), name='uk_idempotency'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['snapshot', 'status'], name='idx_snapshot_status'),
        ),
        migrations.AddConstraint(
            model_name='autoorderjobitem',
            constraint=models.UniqueConstraint(fields=('job', 'user'), name='uk_job_user'),
        ),
    ]
